config/routes.rb
XlsApp::Application.routes.draw do
  resources :meetings


   resources :meetings do
  		collection { post :import }
   end

   root :to => 'meetings#index'
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :address, :building, :city, :country, :day, :description, :latitude, :longitude, :meeting_type, :name, :owner, :phone, :state, :status, :time, :zip

  def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    decoration = find_by_id(row["id"]) || new
	    decoration.attributes = row.to_hash.slice(*accessible_attributes)
	    decoration.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Csv.new(file.path, nil, :ignore)
	  when ".xls" then Excel.new(file.path, nil, :ignore)
	  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end

	def self.to_csv(options = {})
	    CSV.generate(options) do |csv|
	      csv << ["Id","Name","Building","Address","City","State","Zip","Phone","Country","Meeting-Type","Day","Time","Description","Latitude","Longitude","Owner","Status"]
	      Meeting.all.each do |meeting|
	        csv << [meeting.id,meeting.name,meeting.building,meeting.address,meeting.city,meeting.state,meeting.zip,meeting.phone,meeting.country,meeting.meeting_type,meeting.day,meeting.time,meeting.description,meeting.latitude,meeting.longitude,meeting.owner,meeting.status]
	      end
	    end
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  
  def import
    Meeting.import(params[:file])
    redirect_to root_url, notice: "decorations imported."
  end

  def index
    @meetings = Meeting.all

    respond_to do |format|
      format.html # index.html.erb
      format.csv { send_data Meeting.to_csv }
      format.xls { send_data Meeting.to_csv(col_sep: "\t") }
      format.json { render json: @meetings }
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XlsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :building %><br />
    <%= f.text_field :building %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :meeting_type %><br />
    <%= f.text_field :meeting_type %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :owner %><br />
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<%= form_tag import_meetings_path, multipart: true do %>
      <%= label_tag :import_xls %>
      <%= file_field_tag :file %>

      <%= submit_tag "Import" %>
<% end %>

<h1>Listing meetings</h1>

<p>
  Download:
  <%= link_to "CSV", meetings_path(format: "csv") %> |
  <%= link_to "Excel", meetings_path(format: "xls") %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>Building</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Phone</th>
    <th>Country</th>
    <th>Meeting type</th>
    <th>Day</th>
    <th>Time</th>
    <th>Description</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Owner</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.name %></td>
    <td><%= meeting.building %></td>
    <td><%= meeting.address %></td>
    <td><%= meeting.city %></td>
    <td><%= meeting.state %></td>
    <td><%= meeting.zip %></td>
    <td><%= meeting.phone %></td>
    <td><%= meeting.country %></td>
    <td><%= meeting.meeting_type %></td>
    <td><%= meeting.day %></td>
    <td><%= meeting.time %></td>
    <td><%= meeting.description %></td>
    <td><%= meeting.latitude %></td>
    <td><%= meeting.longitude %></td>
    <td><%= meeting.owner %></td>
    <td><%= meeting.status %></td>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Building</Data></Cell>
        <Cell><Data ss:Type="String">Address</Data></Cell>
      </Row>
    <% @meetings.each do |meeting| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= meeting.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= meeting.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= meeting.building %></Data></Cell>
        <Cell><Data ss:Type="String"><%= meeting.address %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @meeting.name %>
</p>

<p>
  <b>Building:</b>
  <%= @meeting.building %>
</p>

<p>
  <b>Address:</b>
  <%= @meeting.address %>
</p>

<p>
  <b>City:</b>
  <%= @meeting.city %>
</p>

<p>
  <b>State:</b>
  <%= @meeting.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @meeting.zip %>
</p>

<p>
  <b>Phone:</b>
  <%= @meeting.phone %>
</p>

<p>
  <b>Country:</b>
  <%= @meeting.country %>
</p>

<p>
  <b>Meeting type:</b>
  <%= @meeting.meeting_type %>
</p>

<p>
  <b>Day:</b>
  <%= @meeting.day %>
</p>

<p>
  <b>Time:</b>
  <%= @meeting.time %>
</p>

<p>
  <b>Description:</b>
  <%= @meeting.description %>
</p>

<p>
  <b>Latitude:</b>
  <%= @meeting.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @meeting.longitude %>
</p>

<p>
  <b>Owner:</b>
  <%= @meeting.owner %>
</p>

<p>
  <b>Status:</b>
  <%= @meeting.status %>
</p>


<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>